#!/usr/bin/env bash
#Displays script the prints some text on a long format
n=1
while [ $n -le 10 ]
do
	if [ $n -eq 4 ]
	then
	    echo "bad luck"
	elif [ $n -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Best School"
	fi
	((n++))
done
